### ISSUE TITLE
Associate clients with chosen display name

### ISSUE THREAD

**Issue by JacobAKnox** [TheFiveMemberTeam/Retrograde-DarkOrbit#2]
US - 1
1 hr

**Comment by JEmersonLawrance** [comment]
My comments:

- The logic for calling join_lobby and handling the server response data looks good for the most part
- See the comments I left in `retrograde-dark-orbit/src/components/display_name_form.js` for feedback and suggestions on that
- The 'handles non-unique usernames correctly' test in `retrograde-dark-orbit/src/components/display_name_form.test.js` needs tweaking, it looks like it's testing

  `{
      status: 'error',
      message: 'Username is already taken'
    }`
    
    as the expected response, but the expected response for an incorrect username according to the `join_lobby` function in `server/lobbies/lobbies.js` would be
    
    `{status: 400, message: 'No lobby with code ${lobby_code}'}`

- The `retrograde-dark-orbit/src/components/display_name_form.test.js` file should probably also test for the successful response as well, because that indicates that the username has been added to the lobby successfully

**Comment by JacobAKnox** [comment]
task complete
